version: '3'

services:
  app-new:
    build:
      context: ./
      args:
        appdir: "/app-new"
    ports:
      - "8081:8080"
    environment:
      OTHER_APP: "app-old:8080"

  # app-old:
  #   build:
  #     context: ./
  #     args:
  #       appdir: "/app-old"
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     OTHER_APP: "app-old:8080"

