version: '3'

services:
  app-new:
    build:
      context: ./
      args:
        app: "new"
    volumes:
      - ./app-new:/app
    ports:
      - "8081:8080"
    environment:
      OTHER_APP: "http://localhost:8081"

  app-old:
    build:
      context: ./
      args:
        app: "old"
    entrypoint: yarn dev
    volumes:
      - ./app-old:/app
    ports:
      - "8082:8080"
    environment:
      OTHER_APP: "http://localhost:8082"

